#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

get_config() {
	config_get_bool enabled $1 enabled 1
	config_get_bool acceptRoutes $1 acceptRoutes 0
	config_get_bool advertiseExitNode $1 advertiseExitNode 0
	config_get loginServer $1 loginServer ""
	config_get authkey $1 authkey ""
	config_get hostname $1 hostname ""
	config_get advertiseRoutes $1 advertiseRoutes ""
}

apply_config() {
	config_load tailscaler
	config_foreach get_config settings
	if [ "$enabled" != 1 ]; then
		stop_service
		return $?
	fi

	logger -t tailscaler 'applying configuration'
	/etc/init.d/tailscale running || /etc/init.d/tailscale start || {
		logger -t tailscaler 'failed to start tailscale'
		return 1
	}

	set -- --reset --timeout=15s
	if [ -n "$loginServer" ]; then
		set -- "$@" --login-server "$loginServer"
	fi
	if [ -n "$authkey" ]; then
		set -- "$@" --auth-key "$authkey"
	fi
	if [ -n "$hostname" ]; then
		set -- "$@" --hostname "$hostname"
	fi
	if [ "$acceptRoutes" = 1 ]; then
		set -- "$@" --accept-routes
	fi
	if [ -n "$advertiseRoutes" ]; then
		set -- "$@" --advertise-routes "$advertiseRoutes"
	fi
	set -- "$@" --accept-dns=false

	/bin/sh /usr/libexec/tailscaler-up "$advertiseExitNode" "$@"
}

start_service() {
	apply_config
}

reload_service() {
	apply_config
}

stop_service() {
	local exit_code=0

	if /etc/init.d/tailscale running; then
		/usr/sbin/tailscale set --advertise-exit-node=false || \
			{
				logger -t tailscaler 'failed to disable exit-node advertisement while stopping'
				exit_code=1
			}
	fi
	/etc/init.d/tailscale stop || exit_code=1
	return "$exit_code"
}

service_triggers() {
	procd_add_reload_trigger tailscaler
}
